// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93TE5xfX5jQvgsTlOmtZmL5ygCzuaQJ4',
    appId: '1:307087082708:web:8df9cc50fb2829ea852741',
    messagingSenderId: '307087082708',
    projectId: 'yepp-91fe5',
    authDomain: 'yepp-91fe5.firebaseapp.com',
    storageBucket: 'yepp-91fe5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKDewNJXHlhOIH5A90rxdrtYKrAD0MiCU',
    appId: '1:307087082708:android:305d7248e8de7688852741',
    messagingSenderId: '307087082708',
    projectId: 'yepp-91fe5',
    storageBucket: 'yepp-91fe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbiAkElewqnk2dpxgMs9s6s8M4SJjAM68',
    appId: '1:307087082708:ios:1e401e10ba2d3ec1852741',
    messagingSenderId: '307087082708',
    projectId: 'yepp-91fe5',
    storageBucket: 'yepp-91fe5.firebasestorage.app',
    iosBundleId: 'com.app.couponCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbiAkElewqnk2dpxgMs9s6s8M4SJjAM68',
    appId: '1:307087082708:ios:1e401e10ba2d3ec1852741',
    messagingSenderId: '307087082708',
    projectId: 'yepp-91fe5',
    storageBucket: 'yepp-91fe5.firebasestorage.app',
    iosBundleId: 'com.app.couponCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA93TE5xfX5jQvgsTlOmtZmL5ygCzuaQJ4',
    appId: '1:307087082708:web:2e93f938e8bb258e852741',
    messagingSenderId: '307087082708',
    projectId: 'yepp-91fe5',
    authDomain: 'yepp-91fe5.firebaseapp.com',
    storageBucket: 'yepp-91fe5.firebasestorage.app',
  );
}
