// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_inEReD0lKuzY2pSld4-sfPHK136tOs',
    appId: '1:191216477482:web:20c68fdc7fc557d4c2ea53',
    messagingSenderId: '191216477482',
    projectId: 'yepp-app',
    authDomain: 'yepp-app.firebaseapp.com',
    storageBucket: 'yepp-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ZPA1YKlwArS_C8JJ4wZgjSaga3OUglM',
    appId: '1:191216477482:android:05ce7fab01d74fefc2ea53',
    messagingSenderId: '191216477482',
    projectId: 'yepp-app',
    storageBucket: 'yepp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5yWlReFjg5yAYXNG_CoTm2mO8oq427I',
    appId: '1:191216477482:ios:47809d2eaee504d3c2ea53',
    messagingSenderId: '191216477482',
    projectId: 'yepp-app',
    storageBucket: 'yepp-app.firebasestorage.app',
    iosBundleId: 'agency.beuptech.yepp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp5yWlReFjg5yAYXNG_CoTm2mO8oq427I',
    appId: '1:191216477482:ios:47809d2eaee504d3c2ea53',
    messagingSenderId: '191216477482',
    projectId: 'yepp-app',
    storageBucket: 'yepp-app.firebasestorage.app',
    iosBundleId: 'agency.beuptech.yepp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6_inEReD0lKuzY2pSld4-sfPHK136tOs',
    appId: '1:191216477482:web:ab0e9cde9a1dc9b8c2ea53',
    messagingSenderId: '191216477482',
    projectId: 'yepp-app',
    authDomain: 'yepp-app.firebaseapp.com',
    storageBucket: 'yepp-app.firebasestorage.app',
  );

}